language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

addons:
  sonarqube: true
env:
  global:
    - secure: 55c12d536b53356e424d8da1d7fc84c0166a44c2
script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner -Dsonar.login=55c12d536b53356e424d8da1d7fc84c0166a44c2