language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

branches:
  only:
    - master

before_script:
  - ./gradlew clean

script:
  - ./gradlew build
  - ./gradlew sonarqube -Dsonar.host.url=https://sonarqube.com -Dsonar.login=55c12d536b53356e424d8da1d7fc84c0166a44c2
  #script:
  #- sonar-scanner -Dsonar.login=
  # other script steps might be done before running the actual SonarQube analysis
